version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: cortexcatalyst-metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3001:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase_password
      MB_DB_HOST: metabase-postgres
      # Optional: Set admin email and password for first setup
      MB_ADMIN_EMAIL: admin@cortexcatalyst.com
      MB_ADMIN_FIRST_NAME: Admin
      MB_ADMIN_LAST_NAME: User
    depends_on:
      - metabase-postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  metabase-postgres:
    image: postgres:15
    container_name: metabase-postgres
    hostname: metabase-postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: metabase_password
    volumes:
      - metabase_postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  metabase_postgres_data:
