CREATE TABLE IF NOT EXISTS signups (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(50),
  country_code VARCHAR(10),
  subject VARCHAR(255) NOT NULL,
  stay_in_loop BOOLEAN DEFAULT false,
  challenge_information_overload BOOLEAN DEFAULT false,
  challenge_difficulty_finding_content BOOLEAN DEFAULT false,
  challenge_personalized_learning BOOLEAN DEFAULT false,
  challenge_slow_knowledge_absorption BOOLEAN DEFAULT false,
  challenge_inconsistent_skill_development BOOLEAN DEFAULT false,
  challenge_lack_realtime_feedback BOOLEAN DEFAULT false,
  challenge_gaps_existing_knowledge BOOLEAN DEFAULT false,
  challenge_limited_time_learning BOOLEAN DEFAULT false,
  challenge_overwhelmed_complex_topics BOOLEAN DEFAULT false,
  challenge_fragmented_resources BOOLEAN DEFAULT false,
  challenge_other BOOLEAN DEFAULT false,
  challenge_other_description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
